apiVersion: v1
kind: ServiceAccount
metadata:
  name: vistora-frontend-sa
  namespace: vistora
  labels:
    app: vistora-frontend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vistora-frontend-role
  namespace: vistora
  labels:
    app: vistora-frontend
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vistora-frontend-rolebinding
  namespace: vistora
  labels:
    app: vistora-frontend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vistora-frontend-role
subjects:
- kind: ServiceAccount
  name: vistora-frontend-sa
  namespace: vistora
