apiVersion: v1
kind: Service
metadata:
  name: vistora-frontend-service
  namespace: vistora
  labels:
    app: vistora-frontend
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: vistora-frontend
    tier: frontend
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
